# Generated by Django 3.0.5 on 2020-08-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('units', models.IntegerField(max_length=100)),
                ('sales', models.IntegerField(max_length=100)),
                ('sale_date', models.CharField(max_length=100)),
            ],
        ),
    ]
