# Generated by Django 3.0.5 on 2020-08-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gqlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='sales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='units',
            field=models.IntegerField(),
        ),
    ]
